export interface Empresa {
    nombre: string,
    nit: string,
    departamento: string,
    ciudad: string,
    direccion: string,
    telefono: string,
    celular: string,
    correo: string,
    contrasena: string,
    actividadPrincipal: string,
    descripcion: string,
    horaMInicio: string,
    horaMFin: string,
    horaTInicio: string,
    horaTFin: string,
    domicilio: string,
    servicios: string,
    informacionAdicional: string,
    estado: boolean,
}