export interface Independiente {
    nombre: string,
    id: string,
    documento: string,
    departamento: string,
    ciudad: string,
    direccion: string,
    telefono: string,
    celular: string,
    correo: string,
    contrasena: string,
    profesion: string,
    descripcion: string,
    domicilio: string,
    servicios: string,
    estado: boolean,
    numFotos: string,
    portafolio: string,
    fotoPerfilInd: string
}